import { GoogleAnalytics } from "@next/third-parties/google";
import type { Metadata, Viewport } from "next";
import "overlayscrollbars/overlayscrollbars.css";
import "./globals.css";
import Client from "@/app/client";
import Server from "@/app/server";

export const metadata: Metadata = {
  title: "Fluina",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f2f2f2" },
    { media: "(prefers-color-scheme: dark)", color: "#0d0d0d" },
  ],
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" data-scroll-behavior="smooth" suppressHydrationWarning>
      <head>
        <Server />
        <link id="theme-favicon" rel="icon" href="/favicon/light.ico" />
        <link
          rel="icon"
          href="/favicon/dark.ico"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          href="/favicon/light.ico"
          media="(prefers-color-scheme: dark)"
        />
        <meta
          name="theme-color"
          content="#f2f2f2"
          media="(prefers-color-scheme: light)"
        />
        <meta
          name="theme-color"
          content="#0d0d0d"
          media="(prefers-color-scheme: dark)"
        />
      </head>
      <body>
        <Client>{children}</Client>
        <GoogleAnalytics gaId="G-BCZSM2BCKX" />
      </body>
    </html>
  );
}
